### ISSUE TITLE
Is there any official documentation anywhere of the API capabilities?

### ISSUE THREAD

**Issue by ArielS1** [andxpto/andgearbest#1]

**Comment by 3cpt** [comment]
Hi. Thanks for the question @kill4food .

At the moment we don't provide any kind of documentation about our wrapper.
In order to see the official Gearbest documentation you need to register as an affiliate.

**Comment by 3cpt** [comment]
@ArielS1 I will close this issue but as I said you need a [affiliate.gearbest](https://affiliate.gearbest.com/) account to see the official documentation.
